apiVersion: v1
kind: Service
metadata:
  name: minecraft-whoami
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  # prefer connecting to same pod, to preserve source IP
  sessionAffinity: None
  ports:
    - name: minecraft
      port: 25565
      protocol: TCP
      nodePort: 30758
      targetPort: minecraft
  selector:
    app: minecraft-whoami
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: minecraft-whoami
  labels:
    app: minecraft-whoami
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minecraft-whoami
  template:
    metadata:
      labels:
        app: minecraft-whoami
    spec:
      containers:
        - name: minecraft-whoami
          image: registry-starfallmc.danya02.ru/minecraft-whoami:v1
          imagePullPolicy: Always
          ports:
            - name: minecraft
              containerPort: 25565

---